platform :ios do
     
     # before_all do
      #  cocoapods
       # increment_build_number
       # gym(scheme: "IosContinuousIntegration", workspace: #”IosContinuousIntegration.xcworkspace", use_legacy_build_api: true)
    #  end
     
      desc "Runs all the tests"
      lane :test do
        scan(device: "iPhone 6s")
      end

desc "Upload to App Store and submit for review"
lane :upload do
  deliver
end
     
    end

